name: static-checks
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, unlocked]
    branches:
      - main
      # - development

permissions: read-all

jobs:
  static-test:
    runs-on: ubuntu-latest
    # env:
    # NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.13.0
          run_install: false
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      # - run: echo '//npm.pkg.github.com/:_authToken=${NPM_TOKEN}' >> .npmrc
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Fetch origin/main
        run: git fetch origin main
      - name: Verify Eslint
        run: pnpm lint:ci
      - name: Verify Prettier
        run: pnpm prettier:ci
